# Generated by Django 4.0.4 on 2022-05-05 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MGadgetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=8192)),
                ('ruby', models.CharField(max_length=8192)),
                ('desc', models.CharField(max_length=8192)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
